### ISSUE TITLE
The version on npm is outdated

### ISSUE THREAD

**Issue by TRex22** [IonicaBizau/node-cli-graph#21]
It seems the version on npm is outdated to the repository version. Please could you publish the most recent version. I really need to make different points have different symbols.

**Comment by IonicaBizau** [comment]
@TRex22 I double checked: the latest version is [`3.2.1`](https://www.npmjs.com/package/cli-graph) and is published on npm. :thought_balloon:

**Comment by TRex22** [comment]
Sorry I realize my mistake. I was using the function-graph npm package

**Comment by IonicaBizau** [comment]
@TRex22 Ah, true... That was the initial name of this module...
